# Generated by Django 3.2.8 on 2023-09-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='room_descript',
            new_name='room_desc',
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='short_descr',
            new_name='short_desc',
        ),
    ]
